// Words for the Foil range and custom colours, spread into the main dictionaries in i18n.ts.
import type { RangeRegion } from './featureState';

export const RANGE_COLOR_JA = {
  secRange: '加工の範囲',
  rangeReset: '範囲をリセット',
  rangeWhere: '場所',
  region: {
    all: '全体',
    art: 'イラスト',
    frame: '枠',
    text: '文字',
    none: 'なし',
  } satisfies Record<RangeRegion, string>,
  regionHint: {
    all: 'カード全体に加工がかかります',
    art: 'イラストの窓の中だけ',
    frame: '枠と名前の帯だけ。イラストはそのまま',
    text: 'カード名の文字だけ',
    none: 'どこにもかけず、ブラシで塗った所だけ',
  } satisfies Record<RangeRegion, string>,
  whereBrushed: 'カスタム',
  baseBadge: 'ベース',
  customHint: '「{r}」をもとに、ブラシで塗り足し・消しをしています',
  invertBadge: '以外',
  invertHint: '反転中: {x}以外にかかります',
  regionQ: '「{r}」',
  toneAt: '「{r}」の明るさ {lo}〜{hi}% の部分',
  rangeFew: 'ほとんど加工がかかっていません。',
  myColors: 'マイカラー',
  rangeTone: '明るさ',
  rangeLo: '明るさの下限',
  rangeHi: '明るさの上限',
  tonePresets: ['すべて', 'ハイライト', '中間調', '暗部'],
  rangeInvert: '反転',
  rangeShow: '範囲を常に表示',
  coverLabel: '加工がかかる面積',
  rangeTiny: '1% 未満',
  rangeNone: 'まだどこにも加工がかかっていません。',
  fixTone: '明るさをすべてに',
  fixInvert: '反転を切る',
  fixPaint: 'ブラシで塗る',
  fixRegion: '全体にする',
  fixPainting: 'カードをなぞると塗り足せます。',
  legendTitle: '校正:',
  legendFoil: '加工あり',
  legendPaper: 'そのまま',
  paint: 'ブラシで塗る',
  paintSub: '加工を塗り足す・消す',
  brush: 'ブラシ',
  brushLead: 'なぞった所に加工を足す・消す',
  brushMode: 'ブラシの種類',
  brushAdd: '足す',
  brushErase: '消す',
  brushSize: 'サイズ',
  brushSoft: 'やわらかさ',
  undo: '取り消し',
  redo: 'やり直し',
  brushClear: '全部消す',
  brushDone: '完了',
  brushKeys: [[['[', ']'], 'サイズ'], [['X'], '足す/消す 切替'], [['Ctrl', 'Z'], '取り消し'], [['Esc'], '完了']] as [string[], string][],
  paintActive: 'ブラシで塗っています',
  paintActiveSub: '「完了」か Esc で戻ります',
  brushDoneSub: '塗った所は残ります',
  preview: 'プレビュー',
  previewJump: 'カードまで戻る',
  previewHide: 'プレビューを隠す',
  previewHideShort: '隠す',
  colorUndo: '元に戻す',
  sizeOf: 'カード幅の {n}%',
  brushOn: 'ブラシモード。カードは正面で止まります',
  brushOff: 'ブラシモードを終了しました',
  brushCleared: '塗った範囲を全部消しました',
  brushUndone: '取り消しました',
  brushRedone: 'やり直しました',
  backdrop: '背景',
  backdropAuto: '自動 (加工に合わせる)',
  backdropAutoShort: '自動',
  backdropName: { felt: 'フェルト', night: 'ナイト', ember: 'エンバー' } as Record<string, string>,
  addFrameColor: '枠の色を追加',
  addStageColor: '背景の色を追加',
  addColor: '色を追加',
  myColor: 'マイカラー {hex}',
  removeColor: '{hex} を削除',
  colorKeys: 'Delete キーで削除',
  colorAdded: '{hex} を追加しました',
  colorRemoved: '色を削除しました',
  colorRemovedFrame: '色を削除し、枠を「{x}」に戻しました',
  colorRemovedStage: '色を削除し、背景を自動に戻しました',
  colorFull: 'マイカラーは {n} 色まで。いちばん古い色と入れ替えました',
};

export type RangeColorDict = typeof RANGE_COLOR_JA;

export const RANGE_COLOR_EN: RangeColorDict = {
  secRange: 'Finish area',
  rangeReset: 'Reset area',
  rangeWhere: 'Where',
  region: {
    all: 'All',
    art: 'Art',
    frame: 'Frame',
    text: 'Name',
    none: 'None',
  },
  regionHint: {
    all: 'The finish covers the whole card',
    art: 'Only inside the art window',
    frame: 'Only the frame and name band; the art stays plain',
    text: 'Only the letters of the card name',
    none: 'Nowhere, except what you paint with the brush',
  },
  whereBrushed: 'Custom',
  baseBadge: 'base',
  customHint: 'Starts from {r}, with brush strokes added or erased',
  invertBadge: 'except',
  invertHint: 'Inverted: everything but {x}',
  regionQ: '{r}',
  toneAt: 'the {lo}–{hi}% tones of {r}',
  rangeFew: 'Almost nothing gets the finish.',
  myColors: 'My colours',
  rangeTone: 'Brightness',
  rangeLo: 'Darkest tone',
  rangeHi: 'Lightest tone',
  tonePresets: ['Full range', 'Highlights', 'Midtones', 'Shadows'],
  rangeInvert: 'Invert',
  rangeShow: 'Pin the proof',
  coverLabel: 'Coverage',
  rangeTiny: '<1%',
  rangeNone: 'Nothing gets the finish yet.',
  fixTone: 'Use every tone',
  fixInvert: 'Turn off invert',
  fixPaint: 'Paint some in',
  fixRegion: 'Use the whole card',
  fixPainting: 'Trace the card to paint some in.',
  legendTitle: 'Proof:',
  legendFoil: 'Finished',
  legendPaper: 'Left plain',
  paint: 'Paint with a brush',
  paintSub: 'Add or erase the finish',
  brush: 'Brush',
  brushLead: 'Trace the card to add or lift the finish',
  brushMode: 'Brush type',
  brushAdd: 'Add',
  brushErase: 'Erase',
  brushSize: 'Size',
  brushSoft: 'Softness',
  undo: 'Undo',
  redo: 'Redo',
  brushClear: 'Clear all',
  brushDone: 'Done',
  brushKeys: [[['[', ']'], 'size'], [['X'], 'switch'], [['Ctrl', 'Z'], 'undo'], [['Esc'], 'done']],
  paintActive: 'Painting',
  paintActiveSub: 'Done or Esc to finish',
  brushDoneSub: 'Your strokes stay',
  preview: 'Preview',
  previewJump: 'Back to the card',
  previewHide: 'Hide preview',
  previewHideShort: 'Hide',
  colorUndo: 'Undo',
  sizeOf: '{n}% of the card width',
  brushOn: 'Brush mode. The card holds still, facing you',
  brushOff: 'Left brush mode',
  brushCleared: 'Cleared everything you painted',
  brushUndone: 'Undone',
  brushRedone: 'Redone',
  backdrop: 'Backdrop',
  backdropAuto: 'Auto (matches the finish)',
  backdropAutoShort: 'Auto',
  backdropName: { felt: 'Felt', night: 'Night', ember: 'Ember' },
  addFrameColor: 'Add a frame colour',
  addStageColor: 'Add a backdrop colour',
  addColor: 'Add colour',
  myColor: 'My colour {hex}',
  removeColor: 'Remove {hex}',
  colorKeys: 'Press Delete to remove',
  colorAdded: 'Added {hex}',
  colorRemoved: 'Colour removed',
  colorRemovedFrame: 'Colour removed; the frame is back to {x}',
  colorRemovedStage: 'Colour removed; the backdrop is back to Auto',
  colorFull: 'Up to {n} colours. Swapped out the oldest one',
};
