// Words for the Foil range and custom colours, spread into the main dictionaries in i18n.ts.
import type { RangeRegion } from './featureState';

export const RANGE_COLOR_JA = {
  secRange: '加工の範囲',
  rangeReset: '範囲をリセット',
  rangeWhere: '場所',
  region: {
    all: '全体',
    art: 'イラスト',
    frame: '枠',
    text: '文字',
    none: 'なし',
  } satisfies Record<RangeRegion, string>,
  regionHint: {
    all: 'カード全体に加工がかかります',
    art: 'イラストの窓の中だけ',
    frame: '枠と名前の帯だけ。イラストはそのまま',
    text: 'カード名の文字だけ',
    none: 'どこにもかけず、ブラシで塗った所だけ',
  } satisfies Record<RangeRegion, string>,
  whereBrushed: '+ ブラシ',
  invertHint: '反転中: 「{x}」以外にかかります',
  rangeTone: '明るさ',
  rangeLo: '明るさの下限',
  rangeHi: '明るさの上限',
  tonePresets: ['すべて', 'ハイライト', '中間', '暗部'],
  rangeInvert: '反転',
  rangeShow: '範囲を表示',
  rangeCover: '加工がかかるのはカードの {n}%',
  rangeTiny: '加工がかかるのはカードの 1% 未満',
  rangeNone: '加工がかかる場所がありません。明るさの幅を広げるか、ブラシで塗り足してください',
  rangeAllCover: 'カード全体に加工がかかっています',
  paint: 'ブラシで塗る',
  paintSub: '加工を塗り足す・消す',
  brush: 'ブラシ',
  brushLead: 'カードをなぞると、そこだけ加工を足したり消したりできます',
  brushMode: 'ブラシの種類',
  brushAdd: '足す',
  brushErase: '消す',
  brushSize: 'サイズ',
  brushSoft: 'やわらかさ',
  undo: '取り消し',
  redo: 'やり直し',
  brushClear: '全部消す',
  brushDone: '完了',
  brushKeys: ['[ ] でサイズ', 'X で足す/消す', 'Ctrl+Z で取り消し', 'Esc で完了'],
  paintActive: 'ブラシで塗っています',
  paintActiveSub: '押すと完了',
  sizeOf: 'カード幅の {n}%',
  brushOn: 'ブラシモード。カードは正面で止まります',
  brushOff: 'ブラシモードを終了しました',
  brushCleared: '塗った範囲を全部消しました',
  brushUndone: '取り消しました',
  brushRedone: 'やり直しました',
  backdrop: '背景',
  backdropAuto: '自動 (加工に合わせる)',
  backdropAutoShort: '自動',
  backdropName: { felt: 'フェルト', night: 'ナイト', ember: 'エンバー' } as Record<string, string>,
  addFrameColor: '枠の色を追加',
  addStageColor: '背景の色を追加',
  addColor: '色を追加',
  myColor: 'マイカラー {hex}',
  removeColor: '{hex} を削除',
  colorKeys: 'Delete キーで削除',
  colorAdded: '{hex} を追加しました',
  colorRemoved: '{hex} を削除しました',
  colorFull: 'マイカラーは {n} 色まで。いちばん古い色と入れ替えました',
};

export type RangeColorDict = typeof RANGE_COLOR_JA;

export const RANGE_COLOR_EN: RangeColorDict = {
  secRange: 'Finish area',
  rangeReset: 'Reset area',
  rangeWhere: 'Where',
  region: {
    all: 'All',
    art: 'Art',
    frame: 'Frame',
    text: 'Text',
    none: 'None',
  },
  regionHint: {
    all: 'The finish covers the whole card',
    art: 'Only inside the art window',
    frame: 'Only the frame and name band; the art stays plain',
    text: 'Only the letters of the card name',
    none: 'Nowhere, except what you paint with the brush',
  },
  whereBrushed: '+ brush',
  invertHint: 'Inverted: everywhere except {x}',
  rangeTone: 'Brightness',
  rangeLo: 'Darkest tone',
  rangeHi: 'Lightest tone',
  tonePresets: ['Every tone', 'Highlights', 'Midtones', 'Shadows'],
  rangeInvert: 'Invert',
  rangeShow: 'Show area',
  rangeCover: 'The finish covers {n}% of the card',
  rangeTiny: 'The finish covers under 1% of the card',
  rangeNone: 'Nothing gets the finish. Widen the brightness or paint some in',
  rangeAllCover: 'The finish covers the whole card',
  paint: 'Paint with a brush',
  paintSub: 'Add or erase the finish',
  brush: 'Brush',
  brushLead: 'Paint over the card to add or erase the finish right there',
  brushMode: 'Brush type',
  brushAdd: 'Add',
  brushErase: 'Erase',
  brushSize: 'Size',
  brushSoft: 'Softness',
  undo: 'Undo',
  redo: 'Redo',
  brushClear: 'Clear all',
  brushDone: 'Done',
  brushKeys: ['[ ] resize', 'X add/erase', 'Ctrl+Z undo', 'Esc done'],
  paintActive: 'Painting',
  paintActiveSub: 'Press to finish',
  sizeOf: '{n}% of the card width',
  brushOn: 'Brush mode. The card holds still, facing you',
  brushOff: 'Left brush mode',
  brushCleared: 'Cleared everything you painted',
  brushUndone: 'Undone',
  brushRedone: 'Redone',
  backdrop: 'Backdrop',
  backdropAuto: 'Auto (matches the finish)',
  backdropAutoShort: 'Auto',
  backdropName: { felt: 'Felt', night: 'Night', ember: 'Ember' },
  addFrameColor: 'Add a frame colour',
  addStageColor: 'Add a backdrop colour',
  addColor: 'Add colour',
  myColor: 'My colour {hex}',
  removeColor: 'Remove {hex}',
  colorKeys: 'Press Delete to remove',
  colorAdded: 'Added {hex}',
  colorRemoved: 'Removed {hex}',
  colorFull: 'Up to {n} colours. Swapped out the oldest one',
};
