// Words for the pack shelf, the folders and the opening, kept under `pack` in the main dictionaries.
import type { PackId } from './packs';

export const PACK_JA = {
  shelf: 'パック',
  name: { metal: '金属', light: '光', nature: '自然', studio: '工房', supporter: 'サポーター' } satisfies Record<PackId, string>,
  title: '{name}パック',
  sealed: '未開封',
  openChip: '{name}パックを開ける ({n}枚入り)',
  folderChip: '{name}のフォルダ — 手札に{n}枚',
  replay: '開封をもう一度見る',
  count: '{n}枚入り',
  dialog: '{name}パックの開封',
  trace: '上の線をなぞって開ける',
  openBtn: '開ける',
  skip: 'スキップ',
  swipe: 'スワイプかタップで次へ',
  charge: 'タップしてめくる',
  showpiece: '目玉',
  supporterTag: 'サポーター限定',
  thanks: '応援ありがとう',
  haul: '手札に「{name}」のフォルダができました',
  haulReplay: '{name}パックの中身',
  haulHint: 'カードを選ぶと、自分の絵ですぐ試せます',
  try: '手札で試す',
  close: '閉じる',
  loading: 'パックを準備中…',
  failed: 'パックを読み込めませんでした。通信を確かめて、もう一度どうぞ',
};

export const PACK_EN: typeof PACK_JA = {
  shelf: 'Packs',
  name: { metal: 'Metal', light: 'Light', nature: 'Nature', studio: 'Studio', supporter: 'Supporter' },
  title: '{name} Pack',
  sealed: 'Sealed',
  openChip: 'Open the {name} pack ({n} finishes)',
  folderChip: '{name} folder — {n} in the hand',
  replay: 'Watch the opening again',
  count: '{n} finishes',
  dialog: 'Opening the {name} pack',
  trace: 'Trace the line to open',
  openBtn: 'Open',
  skip: 'Skip',
  swipe: 'Swipe or tap for the next',
  charge: 'Tap to turn it over',
  showpiece: 'Showpiece',
  supporterTag: 'Supporters only',
  thanks: 'Thank you for the support',
  haul: 'The {name} folder is in your hand now',
  haulReplay: 'Inside the {name} pack',
  haulHint: 'Pick a card to try it on your picture',
  try: 'Try in the hand',
  close: 'Close',
  loading: 'Getting the pack ready…',
  failed: "Couldn't load the pack. Check the connection and try again",
};
