// Words for the pack shelf, the folders and the opening, kept under `pack` in the main dictionaries.
import type { PackId } from './packs';

export const PACK_JA = {
  shelf: 'パック',
  name: { metal: '金属', light: '光', nature: '自然', studio: '工房', supporter: 'サポーター' } satisfies Record<PackId, string>,
  title: '{name}パック',
  sealed: '未開封',
  openChip: '{name}パックを開ける ({n}枚入り)',
  folderChip: '{name}のフォルダ — 手札に{n}枚',
  replay: '開封をもう一度見る',
  replayShort: '見直す',
  count: '{n}種すべて入り',
  dialog: '{name}パックの開封',
  trace: '上の線をなぞって開ける',
  openBtn: 'パックを開ける',
  skip: 'まとめて見る',
  swipe: 'スワイプかタップで次へ',
  charge: 'タップしてめくる',
  showpiece: '目玉',
  supporterTag: 'サポーター',
  thanks: 'FOIL を応援してくれてありがとう',
  haul: '「{name}」の{n}種がそろいました',
  haulSub: '手札の下の「{name}」フォルダに入りました。',
  haulReplay: '{name}パックの中身',
  haulHint: 'カードを選ぶと、自分の絵ですぐ試せます',
  try: '「{finish}」で試す',
  close: '閉じる',
  loading: 'パックを準備中…',
  failed: 'パックを読み込めませんでした。通信を確かめて、もう一度どうぞ',
};

export const PACK_EN: typeof PACK_JA = {
  shelf: 'Packs',
  name: { metal: 'Metal', light: 'Light', nature: 'Nature', studio: 'Studio', supporter: 'Supporter' },
  title: '{name} Pack',
  sealed: 'Sealed',
  openChip: 'Open the {name} pack ({n} finishes)',
  folderChip: '{name} folder — {n} in the hand',
  replay: 'Watch the opening again',
  replayShort: 'Replay',
  count: 'All {n} finishes inside',
  dialog: 'Opening the {name} pack',
  trace: 'Trace the line to open',
  openBtn: 'Open pack',
  skip: 'Show all',
  swipe: 'Swipe or tap for the next',
  charge: 'Tap to turn it over',
  showpiece: 'Showpiece',
  supporterTag: 'Supporter',
  thanks: 'Thank you for supporting FOIL',
  haul: 'You have all {n} {name} finishes',
  haulSub: "They're in the {name} folder under your hand.",
  haulReplay: 'Inside the {name} pack',
  haulHint: 'Tap a card to try it on your picture',
  try: 'Try {finish}',
  close: 'Close',
  loading: 'Getting the pack ready…',
  failed: "Couldn't load the pack. Check the connection and try again",
};
